name: Deploy QuickBill Pro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install
      
    - name: Install backend dependencies  
      working-directory: ./backend
      run: npm install
      
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      
    - name: Test backend health
      working-directory: ./backend
      run: |
        npm start &
        sleep 10
        curl -f http://localhost:3001/api/health || exit 1
        pkill -f "npm start"

  deploy-notification:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deployment Ready
      run: |
        echo "✅ Build successful!"
        echo "🚀 Ready for deployment to Railway and Vercel"
        echo "📖 Check DEPLOYMENT.md for manual deployment steps"